language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: bionic
env:
  global:
    - DEPOPTS="*"
    - TESTS=true
    - DISTRO=ubuntu-18.04
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.02 PACKAGE="kafka"     PINS="kafka:."
  - os: linux
    env: OCAML_VERSION=4.02 PACKAGE="kafka_lwt" PINS="kafka:. kafka_lwt:."
  - os: linux
    env: OCAML_VERSION=4.09 PACKAGE="kafka"     PINS="kafka:."
  - os: linux
    env: OCAML_VERSION=4.00 PACKAGE="kafka_lwt" PINS="kafka:. kafka_lwt:."
  - os: osx
    env: OCAML_VERSION=4.09 PACKAGE="kafka"     PINS="kafka:."
